# PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)
#!nvidia-smi

2.1.2+cu121


## Introduction to Tensors
#### Creating tensors 'torch.tensor()'

In [3]:
# Scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [4]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)

tensor([7, 7])
1


In [5]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([7, 8])
tensor([ 9, 10])
torch.Size([2, 2])


In [6]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR[0])
print(TENSOR[0][1])
print(TENSOR[0][1][2])
print(TENSOR.shape)
print(TENSOR.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(6)
torch.Size([1, 3, 3])
3


## Random Tensors (for randomizing weights when train start)

#### 'torch.rand()'

In [7]:
random_tensor = torch.rand(1, 3, 4)
print(random_tensor)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[[0.0189, 0.9015, 0.1566, 0.8881],
         [0.1720, 0.5203, 0.9192, 0.2344],
         [0.8505, 0.6868, 0.4685, 0.3790]]])
torch.Size([1, 3, 4])
3


In [8]:
random_image_tensor = torch.rand(size=(3, 224,224))
print(random_image_tensor.shape)
print(random_image_tensor.ndim)

torch.Size([3, 224, 224])
3


## Zeros & Ones Tensors (for masking)

#### 'torch.zero'  'torch.ones()'

In [9]:
zeros = torch.zeros(size=(3,4))
print(zeros)
ones = torch.ones(size=(3,4))
print(ones)
zeros.dtype, ones.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


(torch.float32, torch.float32)

## Range of Tensors / tensor-like

#### 'torch.arange()'  'torch.zeros_like()/torch.ones_like()' for shape copy

In [10]:
range = torch.arange(start=0, end=1000, step=100)
print(range)
zeros_like = torch.zeros_like(input=range)
print(zeros_like)
ones_like = torch.ones_like(input=range)
print(ones_like)

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## Tensor Datatypes (good for precision/time balance)
#### default type is float_32

In [11]:
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=torch.float32, # Datatype of tensor
                              device='cuda', # Device the tensor will be on
                              requires_grad=False) # Whether to or no to track gradients with operations
print(float32_tensor) 

float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor) 

tensor([3., 6., 9.], device='cuda:0')
tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)


In [12]:
int32_tensor = torch.tensor([3,4,5], dtype=torch.int32, device='cuda')
int32_tensor

tensor([3, 4, 5], device='cuda:0', dtype=torch.int32)

In [13]:
float16_tensor * int32_tensor

tensor([ 9., 24., 45.], device='cuda:0', dtype=torch.float16)

In [14]:
some_tensor = torch.rand(3,3)
some_tensor, some_tensor.dtype, some_tensor.shape, some_tensor.device

(tensor([[0.7421, 0.0167, 0.8483],
         [0.2411, 0.9997, 0.9720],
         [0.5641, 0.9046, 0.5160]]),
 torch.float32,
 torch.Size([3, 3]),
 device(type='cpu'))

## Manipulating Tensors

In [28]:
tensor = torch.tensor([1,2,3,4,5])
tensor + 10, tensor - 10, tensor * 10, tensor / 10,

(tensor([11, 12, 13, 14, 15]),
 tensor([-9, -8, -7, -6, -5]),
 tensor([10, 20, 30, 40, 50]),
 tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000]))

In [29]:
torch.add(tensor, 10), torch.sub(tensor, 10), torch.mul(tensor, 10), torch.div(tensor, 10)

(tensor([11, 12, 13, 14, 15]),
 tensor([-9, -8, -7, -6, -5]),
 tensor([10, 20, 30, 40, 50]),
 tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000]))

#### Matrix Multiplication (Dot Product)

In [34]:
%time
torch.matmul(tensor, tensor)
tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(55)

In [41]:
torch.matmul(torch.rand([5,10]), torch.rand([10,4])).shape

torch.Size([5, 4])

#### Transpose

In [50]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
tensor_A.shape,tensor_B.shape

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation (min max mean sum)

In [66]:
x = torch.arange(0,10000, step=10)
torch.min(x), x.min(), torch.max(x), x.max(), torch.mean(x.type(torch.float32)), x.type(torch.float32).mean(), torch.sum(x), x.sum()

(tensor(0),
 tensor(0),
 tensor(9990),
 tensor(9990),
 tensor(4995.),
 tensor(4995.),
 tensor(4995000),
 tensor(4995000))

### Postitional min max (arg)

In [67]:
torch.argmin(x), x.argmin(), torch.argmax(x), x.argmax()

(tensor(0), tensor(0), tensor(999), tensor(999))

### Reshaping view stacking squeezing unsqueezing permute

In [115]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [116]:
x_reshaped = x.reshape(1,9) # should sum up to same size
x_reshaped, x_reshaped.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [117]:
z = x.view(1,9) # share same memory as x, changing z changes x
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [118]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [119]:
torch.stack([x,x,x], dim = 1), torch.stack([x,x,x], dim = 0)

(tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [120]:
torch.vstack([x,x,x]), torch.hstack([x,x,x])

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [131]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [132]:
x_reshaped.size()

torch.Size([1, 9])

In [133]:
x_reshaped.squeeze() # removes all 1 dims

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [134]:
x_reshaped.squeeze().shape

torch.Size([9])

In [140]:
x_reshaped.squeeze().unsqueeze(dim=1).shape, x_reshaped.squeeze().unsqueeze(dim=1).unsqueeze(dim=2).shape

(torch.Size([9, 1]), torch.Size([9, 1, 1]))

In [150]:
x_image = torch.rand(size=(224,224,3)) # height width color_channel
x_perm = x_image.permute(2, 0, 1) # rearrange dimensions/axis (usually with images) by indexes
print(x_image.shape, x_perm.shape)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])


In [151]:
x_image[0,0,0] = 720
x_image[0,0,0], x_perm[0,0,0] # is like view

(tensor(720.), tensor(720.))

### Indexing

In [152]:
import torch

In [156]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [161]:
x[0][0][0], x[0][0], x[0]

(tensor(1),
 tensor([1, 2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [165]:
x[:,1] # all of target dim

tensor([[4, 5, 6]])

In [166]:
x[:,:,1] # all val of 0-1 dem but only index 1 of 2nd

tensor([[2, 5, 8]])

In [167]:
x[:,1,1] # all val of 0 dim with only 1 index val of 1 and 2 dim

tensor([5])

In [168]:
x[0,0,:]# get index 0 of 0th and 1st dim and all of 2nd

tensor([1, 2, 3])

### PyTorch Tensors and Numpy

numpy -> tensor   torch.from_numpy(ndarray)

In [173]:
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) # dont share same memory
torch.arange(1.0,8.0), torch.arange(1.0,8.0).dtype, tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32,
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [174]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # dont share same memory
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (taking random out of random)
random seed

In [183]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # flavor only for one block of code
random_tensor_A = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A, random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Accessing a GPU

In [184]:
!nvidia-smi

Sat Feb  3 01:07:15 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.23                 Driver Version: 551.23         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   58C    P8              6W /   90W |     139MiB /   4096MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [188]:
# device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [211]:
# putting tensors and models on gpu
tensor = torch.tensor([1,2,3], device='cpu')
print(tensor, tensor.device)
tensor = tensor.to(device)
print(tensor)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')


In [212]:
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [213]:
# back to cpu for numpy
tensor = tensor.cpu().numpy()
tensor

array([1, 2, 3], dtype=int64)